name             'logstash'
maintainer       'Eneo Tecnología S.L.'
maintainer_email 'git@redborder.com'
license          'AGPL-3.0'
description      'Installs/Configures cookbook-logstash'
version          '8.10.0'
